### ISSUE TITLE
Not reproducible results  

### ISSUE THREAD

**Issue by xbelonogov** [TAMU-VITA/DeblurGANv2#11]
This repository doesn't provide any convenient way to test pretrained model. 
 
I tested model on GoPro dataset 
I used the following simple changes. Check out this commit. 
https://github.com/xbelonogov/DeblurGANv2/commit/c54e4762e9f4e8caca9ee9ddad9f80651726d968

I got the following results. 
```
ssim: 0.8495713622280843  # result from paper "0.934"
psnr: 27.6642065161339    # result from paper "29.55"
```

Let me know if I ran your code incorrectly

**Comment by jiangxiluning** [comment]
@xbelonogov hi, could you give me the fpn_inception.h5?

**Comment by xbelonogov** [comment]
@jiangxiluning I just downloaded it by the link in readme.md from Google drive

**Comment by jiangxiluning** [comment]
@xbelonogov the link is broken.

**Comment by xbelonogov** [comment]
Yes, It's not clickable for some reason, but you can copy [it.](https://drive.google.com/open?id=1hv238vS9VeK8C8QwrQ2MnJc3ChgHyaGy)  ;)

**Comment by Thebluebluesky** [comment]
Hi， I got a problem when I run this code, I can you tell me where did you find the "pretrainedmodels/inceptionresnetv2“ model. which was pretrained through ImageNet and used in Train.init_param.

**Comment by Thebluebluesky** [comment]
> This repository doesn't provide any convenient way to test pretrained model.
> 
> I tested model on GoPro dataset
> I used the following simple changes. Check out this commit.
> [xbelonogov@c54e476](https://github.com/xbelonogov/DeblurGANv2/commit/c54e4762e9f4e8caca9ee9ddad9f80651726d968)
> 
> I got the following results.
> 
> ```
> ssim: 0.8495713622280843  # result from paper "0.934"
> psnr: 27.6642065161339    # result from paper "29.55"
> ```
> 
> Let me know if I ran your code incorrectly

You should change "bounds" to [0,1] in "config.yaml". But even change that, I only got lower PSNR and SSIM, I don't know why

**Comment by dyfloveslife** [comment]
> Hi， I got a problem when I run this code, I can you tell me where did you find the "pretrainedmodels/inceptionresnetv2“ model. which was pretrained through ImageNet and used in Train.init_param.

Please use "pip install pretrainedmodels" to install this package.

**Comment by yhjo09** [comment]
Similar problem, predict.py does not reproduce results using provided fpn_inception.h5.
I got SSIM 0.8470.

**Comment by enjoybo** [comment]
the same problems

**Comment by nwpuhq** [comment]
why didnt reproduce the results paper reported??
Is there anybody did it?

**Comment by nwpuhq** [comment]
@xbelonogov  Excuse me.Did you reproduce the result?

**Comment by KupynOrest** [comment]
There is a bug in the inference, will be updated soon

**Comment by Thebluebluesky** [comment]
> There is a bug in the inference, will be updated soon

It has been half a month, is the bug still unfixed?

**Comment by QYD123** [comment]
I get the result : PSNR:28.00 (calculated by utils.metrics.PSNR), SSIM: 0.85(caculated by skimage.metrics._structural_similarity) on the GOPRO dataset using best_fpn.h5. The ssim result is lower than that in the paper, Is it because we use the same method of calculating ssim? Or is it another reason?@KupynOrest

**Comment by QYD123** [comment]
I get the result : PSNR:19.96 (calculated by utils.metrics.PSNR), SSIM: 0.55(caculated by skimage.metrics._structural_similarity) on the Kohler dataset using best_fpn.h5. The result both are much lower than that in paper.@KupynOrest

**Comment by Thebluebluesky** [comment]
> There is a bug in the inference, will be updated soon

Hi, I think maybe you are so busy that you forgot to fix this bug. Why don't you just tell us where the bug is, so we can fix it ourselves. It 's been a month, I will very much appreciate that if you can just tell us the problem. @KupynOrest

**Comment by t-martyniuk** [comment]
please check the updated testing routine and updated links to the weights in readme

**Comment by NoviceCrom** [comment]
> I get the result : PSNR:28.00 (calculated by utils.metrics.PSNR), SSIM: 0.85(caculated by skimage.metrics._structural_similarity) on the GOPRO dataset using best_fpn.h5. The ssim result is lower than that in the paper, Is it because we use the same method of calculating ssim? Or is it another reason?@KupynOrest

What's your GOPRO dataset size? Is it the 9G one or the complete version of 30+G?
