### ISSUE TITLE
adversarail loss got negative value

### ISSUE THREAD

**Issue by Xingyb14** [TAMU-VITA/DeblurGANv2#12]
Hi~ 
Thanks for your work.
I printed the loss. It confused me that the adv loss got negative value and D loss is equal to 0 all the time.

Here is my log:
epoch: 554/5000
G_loss=-0.3759; G_loss_content=0.0664; G_loss_adv=-0.4422; D_loss=0.0000; PSNR=23.0817; SSIM=0.7117
time spent: 17:59:02.860182 time remain: 5 days, 12:53:57.710205 107.61s/epoch
epoch: 555/5000
G_loss=0.0658; G_loss_content=0.0636; G_loss_adv=0.0022; D_loss=0.0000; PSNR=22.2133; SSIM=0.6799
time spent: 18:01:14.923619 time remain: 6 days, 19:03:34.153112 132.06s/epoch
epoch: 556/5000
G_loss=-0.2186; G_loss_content=0.0646; G_loss_adv=-0.2832; D_loss=0.0000; PSNR=21.4166; SSIM=0.6062
time spent: 18:03:03.482869 time remain: 5 days, 14:00:28.552603 108.56s/epoch

**Comment by nanfangzhe** [comment]
> 你好~
> 谢谢你的工作。
> 我打印了损失。令我困惑的是，adv loss 为负值，而 D loss 一直等于 0。
> 
> 这是我的日志：
> 纪元：554/5000
> G_loss=-0.3759; G_loss_content=0.0664; G_loss_adv=-0.4422; D_loss=0.0000; PSNR=23.0817；SSIM=0.7117
> 花费时间：17:59:02.860182 剩余时间：5 天，12:53:57.710205 107.61s/epoch
> epoch：555/5000
> G_loss=0.0658；G_loss_content=0.0636; G_loss_adv=0.0022; D_loss=0.0000; PSNR=22.2133；SSIM=0.6799
> 花费时间：18:01:14.923619 剩余时间：6 天，19:03:34.153112 132.06s/epoch
> epoch：556/5000
> G_loss=-0.2186；G_loss_content=0.0646; G_loss_adv=-0.2832; D_loss=0.0000; PSNR=21.4166；SSIM=0.6062
> 花费时间：18:03:03.482869 剩余时间：5 天，14:00:28.552603 108.56s/epoch

Hello, when I run the code again, I encountered the same problem as it was given to you. Is your problem solved and how is it solved?

**Comment by 1039962658** [comment]
me too, how to solve?
