### ISSUE TITLE
 Unexpected key(s) in state_dict: "model"

### ISSUE THREAD

**Issue by frozenbananana** [TAMU-VITA/DeblurGANv2#13]
Hi，I can't load the pretrain model and it prompts me “ Missing key(s) ”. There are something wrong with my operations or pretrain model? Thanks~

**Comment by t-martyniuk** [comment]
Probably you haven't changed the type of g_model in the config file: it expects fpn_inception, but if you use fpn_mobilenet - you have to state it in the config.

If it's something else - please, post a detailed description of your problem, the error message, etc.
