### ISSUE TITLE
No module named 'pretrainedmodels'

### ISSUE THREAD

**Issue by Thebluebluesky** [TAMU-VITA/DeblurGANv2#14]
when I run the code, I got this error
Is anyone know where I can find the pretrained  inceptionresnetv2 model?
Thank you!

> Traceback (most recent call last):
>   File "D:/PyProject/DeblurGANv2/train.py", line 17, in <module>
>     from models.networks import get_nets
>   File "D:\PyProject\DeblurGANv2\models\networks.py", line 8, in <module>
>     from models.fpn_inception import FPNInception
>   File "D:\PyProject\DeblurGANv2\models\fpn_inception.py", line 3, in <module>
>     from pretrainedmodels import inceptionresnetv2
> ModuleNotFoundError: No module named 'pretrainedmodels'

**Comment by dyfloveslife** [comment]
Please use "pip install pretrainedmodels" to install "pretrainedmodels" package : )

**Comment by Thebluebluesky** [comment]
> Please use "pip install pretrainedmodels" to install "pretrainedmodels" package : )

That works. Thank you very much : )
