### ISSUE TITLE
I don't known how to adress this question or my operation is error？ thank you

### ISSUE THREAD

**Issue by congratulation888** [TAMU-VITA/DeblurGANv2#16]
(wzs) student@rtxserver:~/DeblurGANv2-master$ python train.py
W0916 21:22:00.635229 29048 warnings.py:99] train.py:172: YAMLLoadWarning: calling yaml.load() wit                               hout Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org                               /load for full details.
  config = yaml.load(f)

I0916 21:22:00.642313 29048 dataset.py:28] Subsampling buckets from 0 to 90.0, total buckets numbe                               r is 100
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    train, val = map(get_dataloader, datasets)
  File "/home/student/DeblurGANv2-master/dataset.py", line 133, in from_config
    files_a, files_b = map(list, zip(*data))
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by Thebluebluesky** [comment]
Change  your data dir from *.jpg to *.png in "config.yaml"

**Comment by congratulation888** [comment]
> Change  your data dir from *.jpg to *.png in "config.yaml"

thankyou i will try to your suggestion.

**Comment by congratulation888** [comment]
> 在“ config.yaml”中将数据目录从* .jpg更改为* .png

Hello, can you give a detailed description of config. yaml configuration? The new watch is too difficult to correct。

**Comment by lyp19921126** [comment]
> > 在“ config.yaml”中将数据目录从* .jpg更改为* .png
> 
> Hello, can you give a detailed description of config. yaml configuration? The new watch is too difficult to correct。

have you solve the problem?

**Comment by Thebluebluesky** [comment]
check your data directory seeting in config.yaml, this problem is caused when the program read no data from that directory

**Comment by t-martyniuk** [comment]
thanks, @Thebluebluesky 
yes, please just double-check whether your file paths are consistent.

**Comment by lyp19921126** [comment]
> thanks, @Thebluebluesky
> yes, please just double-check whether your file paths are consistent.
![2019-11-07 20-24-28屏幕截图](https://user-images.githubusercontent.com/47971541/68389032-f11da800-019c-11ea-98fb-f58b31abe0a7.png)
the picture are in the dir but ,what should i do?thanks

**Comment by lyp19921126** [comment]
> check your data directory seeting in config.yaml, this problem is caused when the program read no data from that directory

![2019-11-07 20-24-28屏幕截图](https://user-images.githubusercontent.com/47971541/68389124-32ae5300-019d-11ea-97a6-dc975fcfc56b.png)
the picture are in the dir but ,what should i do?thanks
