### ISSUE TITLE
problem in dataset.py

### ISSUE THREAD

**Issue by hala3** [TAMU-VITA/DeblurGANv2#17]
msg = f'Subsampling buckets from {lower_bound} to {upper_bound}, total buckets number is {n_buckets}'
                                                                                                        ^
SyntaxError: invalid syntax

what is the problem ??

**Comment by dyfloveslife** [comment]
https://cito.github.io/blog/f-strings/ 
Not an error. Please see above website.

**Comment by t-martyniuk** [comment]
just use Python 3.6+
