### ISSUE TITLE
Anyone came across that the upper left corner of the image appears "purple".

### ISSUE THREAD

**Issue by xiaozhi2015** [TAMU-VITA/DeblurGANv2#18]
![image](https://user-images.githubusercontent.com/12682406/65657113-b16b8880-e054-11e9-8711-05c8f510a8bc.png)
![image](https://user-images.githubusercontent.com/12682406/65657146-cb0cd000-e054-11e9-806a-b4145ba25948.png)

**Comment by xiaozhi2015** [comment]
And it appears in almost every result image.

**Comment by KupynOrest** [comment]
There is a bug in the inference, will be updated soon

**Comment by xiaozhi2015** [comment]
Thx for your quick reply, looking forward to the update...

**Comment by vgg4resnet** [comment]
yes，has this  been solved? I test my images ，filled in my all images， not only  the corner of images， is it this caused by np.transpose  function?

**Comment by vgg4resnet** [comment]
so is that caused by the network is not converged？my predict result images  were like this
![image](https://user-images.githubusercontent.com/44825736/66456319-e7baf600-ea9f-11e9-9b73-0c79add5cbc6.png)

**Comment by vgg4resnet** [comment]
my training images are gray ，I convert them to BGR format,I also remove the hsv,rgb,transform part by changing the config.yaml

![image](https://user-images.githubusercontent.com/44825736/66468094-2a88c800-eab8-11e9-8353-87efebc15237.png)
the result keep the same ,anywhere maybe lead the problem?By the way  I also remove sharpen part，why do we need that?

**Comment by t-martyniuk** [comment]
please check the updated links to models (latest changes to readme).
should work fine now

**Comment by xiaozhi2015** [comment]
Much thx.

**Comment by htleeab** [comment]
There is still some purple artifact on images with new pre-trained model. 
For example:
![image](https://user-images.githubusercontent.com/22631588/78865513-51788480-7a70-11ea-9718-904e393fd827.png)
![image](https://user-images.githubusercontent.com/22631588/78865387-1aa26e80-7a70-11ea-9282-f49d428cec1e.png)
![image](https://user-images.githubusercontent.com/22631588/78865637-87b60400-7a70-11ea-8479-e436bed45337.png)
![image](https://user-images.githubusercontent.com/22631588/78865654-913f6c00-7a70-11ea-8d72-0d1f50434360.png)
![image](https://user-images.githubusercontent.com/22631588/78865830-eaa79b00-7a70-11ea-9d10-bb9c95504aed.png)

It seems that relatively dark region/texture prone to have this artifact. When generating video, it trend to have artifact on same object (but not every frames)
Do anyone have idea why this issue happen?

**Comment by Sandbox3aster** [comment]
@htleeab Which image in GoPro did you test on and which model did you use? Let me see if i can reproduce that

**Comment by htleeab** [comment]
Those image are my own test assets, not GoPro dataset. I used the pretrained InceptionResNet-v2 (md5sum: 96f747f38a0119669265cbb5fc7b3c5c)
![05APR_955](https://user-images.githubusercontent.com/22631588/87893490-a87bf580-ca72-11ea-9a46-5c71419d4a8e.png)
![05APR_1993](https://user-images.githubusercontent.com/22631588/87893493-aade4f80-ca72-11ea-843a-1e4202b01c5a.png)
![05APR_1903](https://user-images.githubusercontent.com/22631588/87893496-ac0f7c80-ca72-11ea-8f58-2fc131378212.png)
![05APR_1425](https://user-images.githubusercontent.com/22631588/87893497-aca81300-ca72-11ea-8775-4f8d6e71c89f.png)
![05APR_1176](https://user-images.githubusercontent.com/22631588/87893499-add94000-ca72-11ea-8539-9d18c2febb99.png)
![05APR_1085](https://user-images.githubusercontent.com/22631588/87893501-ae71d680-ca72-11ea-9294-d7d0dac5fc6b.png)
Thanks.

**Comment by Johnreidsilver** [comment]
Same problem here, using cpu and same model  
96f747f38a0119669265cbb5fc7b3c5c  best_fpn.h5

Ubuntu 18.04.02, python 3.6.9
