### ISSUE TITLE
Question about your code

### ISSUE THREAD

**Issue by UtopiaHu** [TAMU-VITA/DeblurGANv2#19]
Hi,
Thank you for your excellent work. When I was running your code, I noticed that you set the parameter 'retain_graph=True' when the discriminator  D was updated. Could you explain why ?

**Comment by t-martyniuk** [comment]
you have to do so because few lines below you have loss_G.backward() and you don't want the information on gradients to be destroyed during the first backprop pass. retain_graph=True keeps the info, and then, when you perform loss_G.backward(), it clears the memory as that info is no more needed.
