### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by xytmhy** [TAMU-VITA/DeblurGANv2#2]
Hi~

Thanks for your work. I have read the DeblurGANv1 paper several month ago and DeblurGANv2 as soon as I can.
Recently, I 'm dealing with my paper of deblur task, I really want to quote and compare with your V2 result in it. May I ask when would you upload your pre-trained model?
It will be very helpful and thank you!

**Comment by lycutter** [comment]
looking forward to the pretrained code

**Comment by lycutter** [comment]
looking forward to the pretrained model too.

**Comment by SreeHarshaNelaturu** [comment]
Is there any evaluation script provided for the same?

**Comment by xytmhy** [comment]
> Is there any evaluation script provided for the same?

Just use PSNR and SSIM, which are commonly used in image restoration tasks

**Comment by KupynOrest** [comment]
The repo was updated with the weights, more coming

**Comment by Giorat** [comment]
Can you publish a script or guide on how to use the pretrained model on simple images?

**Comment by SreeHarshaNelaturu** [comment]
> Can you publish a script or guide on how to use the pretrained model on simple images?

Earlier comment was related to this^

**Comment by Thebluebluesky** [comment]
> The repo was updated with the weights, more coming

The pretrained model link is now 404. Can you publish that again?

**Comment by idealboy** [comment]
> > The repo was updated with the weights, more coming
> 
> The pretrained model link is now 404. Can you publish that again?

I think you can copy the url, and paste it in the explorer, and then you can get the model.

or, you can change the open to us, try it.

**Comment by t-martyniuk** [comment]
- predict.py is the inference code
- the weights are already there (you have to copy links not to get 404 error) - but few fixes are needed, will be updated soon
