### ISSUE TITLE
SSIM reproduction in either DeblurGANV2, V1

### ISSUE THREAD

**Issue by cwr8401** [TAMU-VITA/DeblurGANv2#20]
Hi,

Could you expose which SSIM was used? Did you use CW-SSIM from pyssim package?
People in this and your previous [repo](https://github.com/KupynOrest/DeblurGAN) looking for the answer for reproducing the SSIM reported in your papers.
It seems none of individuals could get higher than 0.9 with the trained weights.

Thanks for any comments

**Comment by t-martyniuk** [comment]
please check test_metrics.py and updated links to the pretrained models
