### ISSUE TITLE
Impossible to convert the pre-trained H5 model to TFLITE

### ISSUE THREAD

**Issue by Jars-of-jam-Scheduler** [TAMU-VITA/DeblurGANv2#22]
Hello,

Just for your information, I was unable to convert your pre-trained H5 model to TFLITE one using this colab cell:

```
import tensorflow as tf
model = tf.keras.models.load_model('/content/drive/.../your_model.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("/content/drive/.../your_model.tflite", "wb").write(tflite_model)
```

The error was:

> OSError: SavedModel file does not exist at: /content/drive/.../your_model.h5/{saved_model.pbtxt|saved_model.pb}

**Comment by caoyangcr7** [comment]
@Jars-of-jam-Scheduler Could you please email me the pre-trained model? the download link has something wrong....my eamil is yangcaocr7@163.com, Thanks

**Comment by Sandbox3aster** [comment]
I think that error is model path related, make sure you enter the path correctly

**Comment by dh4805506** [comment]
> 你好，
> 
> 仅供参考，我无法使用此 colab 单元将您预先训练的 H5 模型转换为 TFLITE 模型：
> 
> ```
> import tensorflow as tf
> model = tf.keras.models.load_model('/content/drive/.../your_model.h5')
> converter = tf.lite.TFLiteConverter.from_keras_model(model)
> tflite_model = converter.convert()
> open("/content/drive/.../your_model.tflite", "wb").write(tflite_model)
> ```
> 
> 错误是：
> 
> > OSError: SavedModel 文件不存在于：/content/drive/.../your_model.h5/{saved_model.pbtxt|saved_model.pb}

Hello, have you solved this problem, I also encountered it
