### ISSUE TITLE
The effect may not be consistent with the result given by the article

### ISSUE THREAD

**Issue by Han-Huaqiao** [TAMU-VITA/DeblurGANv2#23]
Now,when I run "python predict.py face2.jpg",the comparison with the article is as follows:
![deblur](https://user-images.githubusercontent.com/41456966/67450721-e61d3080-f650-11e9-9936-1191b6352398.png)

The two pictures have different effects,Why?

**Comment by MorningStarJ** [comment]
@Han-Huaqiao Hi.
Have you solved the problem?
