### ISSUE TITLE
Question about the pretrained model

### ISSUE THREAD

**Issue by c9o** [TAMU-VITA/DeblurGANv2#24]
Hi,
FPN-inception model performs very good in my tests. I have two questions:
1. The color in the top-left corner seems to be strange. Is there something wrong?
2. I want to repeat your training process. What is your training config and dataset?

Thanks.

**Comment by CounterLiver** [comment]
I got the pretrainedmodel from https://github.com/Cadene/pretrained-models.pytorch/tree/master/pretrainedmodels/models. Maybe this can help you.

**Comment by t-martyniuk** [comment]
please check the reuploaded model (latest change to readme)

you can download the datasets via the links provided in readme, and please add the dataset paths to the training config. all other config parameters remain the same.
