### ISSUE TITLE
The Link of Pretrained model is lost.

### ISSUE THREAD

**Issue by Feywell** [TAMU-VITA/DeblurGANv2#25]
Can you provide the new link? Thank you!

**Comment by t-martyniuk** [comment]
please check the latest update to readme

**Comment by mehameha998** [comment]
It looks like that the download link is crashed agian? @t-martyniuk

**Comment by dyfloveslife** [comment]
> It looks like that the download link is crashed agian? @t-martyniuk

Please copy url and paste it into the addrss bar. Don't click on the link directly.

**Comment by mehameha998** [comment]
Thx! @dyfloveslife  emz....
