### ISSUE TITLE
Port to tensorflow.js

### ISSUE THREAD

**Issue by MariasStory** [TAMU-VITA/DeblurGANv2#3]
Hi,
Thanks for your work.
Taking into account that your solution should be fast, will you be porting/converting trained models to tensorflow.js?

**Comment by MariasStory** [comment]
You can check this one:
https://github.com/tensorflow/tfjs-converter

**Comment by KupynOrest** [comment]
We weren't planning to convert the models to tfjs but if anyone want to do the conversion and send the PR we would strongly appreciate the help
