### ISSUE TITLE
Could you please provide mobilenetv2.pth.tar when use fpn_mobilenet as generator

### ISSUE THREAD

**Issue by wanghaiboanhui** [TAMU-VITA/DeblurGANv2#31]
When I use config['model']['g_name']=fpn_mobilenet, the project come with FileNotFoundError: [Errno 2] No such file or directory: 'mobilenetv2.pth.tar'. Could you please provide this tar file

**Comment by wakanawakana** [comment]
file was not found
Why was it closed?

**Comment by MrWXfaster** [comment]
> file was not found
> Why was it closed?

me too

**Comment by wanghaiboanhui** [comment]
it could run well




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月2日(星期一) 上午9:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [VITA-Group/DeblurGANv2] Could you please provide mobilenetv2.pth.tar when use fpn_mobilenet as generator (#31)





  
file was not found
 Why was it closed?
  
me too

**Comment by V1ct0ryan** [comment]
> it could run well
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年8月2日(星期一) 上午9:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [VITA-Group/DeblurGANv2] Could you please provide mobilenetv2.pth.tar when use fpn_mobilenet as generator (#31) file was not found Why was it closed? me too — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

您好请问如何将mobilenet的跑通呢，谢谢
