### ISSUE TITLE
Would you please tell me 'file_a' and 'file_b' mean? 

### ISSUE THREAD

**Issue by YouSenRong** [TAMU-VITA/DeblurGANv2#33]
I want to run train.py but I don't how to organize the data file path. I am no clear about the 'files_a' and 'files_b' means. Would please tell me how can I organize the data. Thanks a lot.

**Comment by BrainPotter** [comment]
I also want to know this. I use the GoPro dataset and I don't change anything in data file path such as "files_a" and "files_b", and I get very bad results. It seems like the training process didn't work like I think.

**Comment by dyfloveslife** [comment]
1. First, you should modify the `config.yaml` file in the `DeblurGANv2-master/config` folder!
For example:
```
train:
  files_a: ./datasets/my_dataset/train/**/blur/*.png
  files_b: ./datasets/my_dataset/train/**/sharp/*.png
  ...
  ...

val:
  files_a: ./datasets/my_dataset/test/**/blur/*.png
  files_b: ./datasets/my_dataset/test/**/blur/*.png
  ...
  ...
```
2. Then, download [GoPro dataset](https://drive.google.com/file/d/1KStHiZn5TNm2mo3OLZLjnRvd0vVFCI0W/view) that contains `test` folder and `train` folder. 
    - You should put the `train` folder under the `./datasets/my_dataset/` folder, 
    - and put the `test` folder under the `./datasets/my_dataset/` folder.
3. Run `python train.py`, it works.

**Comment by BrainPotter** [comment]
> 1. First, you should modify the `config.yaml` file in the `DeblurGANv2-master/config` folder!
>    For example:
> 
> ```
> train:
>   files_a: ./datasets/my_dataset/train/**/blur/*.png
>   files_b: ./datasets/my_dataset/train/**/sharp/*.png
>   ...
>   ...
> 
> val:
>   files_a: ./datasets/my_dataset/test/**/blur/*.png
>   files_b: ./datasets/my_dataset/test/**/sharp/*.png
>   ...
>   ...
> ```
> 
> 1. Then, download [GoPro dataset](https://drive.google.com/file/d/1KStHiZn5TNm2mo3OLZLjnRvd0vVFCI0W/view) that contains `test` folder and `train` folder.
>    
>    * You should put the `train` folder under the `./datasets/my_dataset/` folder,
>    * and put the `test` folder under the `./datasets/my_dataset/` folder.
> 2. Run `python train.py`, it works.

It works. Thank you very much！

**Comment by universewill** [comment]
mark
