### ISSUE TITLE
I can't find the mobilenetv2.pth.tar when use fpn_mobilenet as generator. can you provide it , thanks!

### ISSUE THREAD

**Issue by nbu-lhj** [TAMU-VITA/DeblurGANv2#36]

**Comment by xuzhiyuan95** [comment]
我有，需要的话可以找我要

**Comment by nbu-lhj** [comment]
感谢。 麻烦发我下~  385746894@qq.com

**Comment by hust-lidelong** [comment]
能否发我一份，谢谢！292042943@qq.com

**Comment by Kuekua** [comment]
> 我有，需要的话可以找我要

能否发我一份，谢谢！wj.bob@163.com

**Comment by YFJIE** [comment]
Here's the download url. You can download it here.
http://sceneparsing.csail.mit.edu/model/pretrained_resnet/mobilenet_v2.pth.tar

**Comment by dcynice** [comment]
> 我有，需要的话可以

> 我有，需要的话可以找我要

你好，叨扰您了， 在测试时候原文中作者用的是 predict.py 来测试效果，但是我看它好像只能一张一张的测试，也没有给出测试时的具体路径设置，请问在predict.py 中需要修改些什么吗？谢谢！

**Comment by Lie-huo** [comment]
能否发我一份，谢谢！shiqiang0708@qq.com

**Comment by gvprudvitej** [comment]
Where should the mobilenetv2.pth.tar be placed i.e., in which folder

**Comment by yff0815** [comment]
感谢。 麻烦发我下~ 1065851036@qq.com

**Comment by t-martyniuk** [comment]
https://drive.google.com/file/d/1srJbh9olqv4zeTi2VqtXQhqe8dM6ED-2/view?usp=sharing

please use this link

**Comment by zhentang777** [comment]
请发一份给我，万分感谢1910294003@mail.szu.edu.cn

**Comment by xuzhiyuan95** [comment]
太大了。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VITA-Group/DeblurGANv2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 中午12:22
收件人:&nbsp;"VITA-Group/DeblurGANv2"<DeblurGANv2@noreply.github.com&gt;;
抄送:&nbsp;"986731614"<986731614@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [VITA-Group/DeblurGANv2] I can't find the mobilenetv2.pth.tar when use fpn_mobilenet as generator. can you provide it , thanks! (#36)





 
请发一份给我，万分感谢1910294003@mail.szu.edu.cn

**Comment by icm162** [comment]
for testing, fpn_mobilenet L20 pretrain=False

**Comment by hust-lidelong** [comment]
已收到邮件，谢谢
