### ISSUE TITLE
cannot import name 'inceptionresnetv2'

### ISSUE THREAD

**Issue by dcynice** [TAMU-VITA/DeblurGANv2#43]
I'm sorry to bother you. I want to retrain the model by myself, but the following errors will occur:
The from pretrainedmodels import inceptionresnetv2
ImportError: cannot import name 'inceptionresnetv2'
May I ask how to solve this problem? Thank you very much

**Comment by vegetable09** [comment]
download it from https://data.lip6.fr/cadene/pretrainedmodels/inceptionresnetv2-520b38e4.pth
then move it to dir /root/.cache/torch/checkpoints/

**Comment by suke27** [comment]
Hello, https://data.lip6.fr/cadene/pretrainedmodels/inceptionresnetv2-520b38e4.pth is invalid is there any other link for it?

**Comment by t-martyniuk** [comment]
hello, I have pretrainedmodels==0.7.4 version
when I type from pretrainedmodels import inceptionresnetv2 - it works for me


<img width="518" alt="Screenshot 2020-07-18 at 08 55 21" src="https://user-images.githubusercontent.com/26787339/87845915-76349180-c8d4-11ea-91b0-aa24953412d9.png">
