### ISSUE TITLE
How to test a 256×256 image？

### ISSUE THREAD

**Issue by yff0815** [TAMU-VITA/DeblurGANv2#49]
Hello ，good work, but I have a question.
I want to test your model in my own data with the size of 256×256, and when I run the command with

 `python test_metrics.py --img_folder=./datasets/my_dataset/ --weights_path=./best_fpn.h5`

the program will result in an error,

`ValueError: operands could not be broadcast together with shapes (720,1280,3) (256,256,3) `

I would like to know why the input with an image of 256×256×3, and then the output with the size of 720×1280×3.
Looking forward to your reply?

**Comment by lisishen** [comment]
Hello, How to generate this file"best_fpn.h5", Is it generated form training? Thanks!

**Comment by yff0815** [comment]
yes, I retrained the network,  it generated the file "best_fpn.h5" and "lasted_fpn.h5".

**Comment by lisishen** [comment]
> yes, I retrained the network, it generated the file "best_fpn.h5" and "lasted_fpn.h5".

WOW! How long does the training take? I found the picture resources is more than 10G.

**Comment by yff0815** [comment]
more than 1day with 1080GTX.

**Comment by pp00704831** [comment]
Hello, may I ask you which datasets do you use to train ?
Because you spend just for more than 1 day, did you use only GoPro for training?
Thank You!

**Comment by yff0815** [comment]
yes, I train the network only using the GoPro dataset, which contains 2013 images to train and 1111 images to test. 
by the way, I'd like to know how to test images with the size of 256×256，do you have any idea?

**Comment by pp00704831** [comment]
I got it, I am training the network right now.
![image](https://user-images.githubusercontent.com/57279608/75446689-d4eb8400-59a2-11ea-9179-d2ccff247e86.png)
I am not sure about your question, but may you can change the size here to (256,256)?
You can try that for some test.

**Comment by yff0815** [comment]
It works. Thank you very much!

**Comment by pp00704831** [comment]
So, do you finish to test?
When I tested with the test_metrics.py, it run pretty slowly for testing it should run quickly when only testing, so i have not finished the test part.
And do you also download the GoPro datasets author given? Because i have about 2200 images for testing.

**Comment by yff0815** [comment]
I spent about 8 minutes to test the GoPro dataset, which has 1111 test images with a size of 720×1280.  I use 1080GTX.
And testing a 256×256 image run fast.

**Comment by pp00704831** [comment]
I got it, Thank you very much!

**Comment by pp00704831** [comment]
![image](https://user-images.githubusercontent.com/57279608/75551239-b357ce80-5a6e-11ea-835f-fc75404d5f67.png)
It looks pretty strange that i need to run so long for test...
I will try to solve that thank you!

**Comment by yff0815** [comment]
![image](https://user-images.githubusercontent.com/41831614/75554945-48aa9100-5a76-11ea-912f-5d3dfcb977cb.png)
when I test 720×1280 images. You can refer to the usage time of each picture.

**Comment by lisishen** [comment]
> I trained 200 epochs, spending more than 1day with 1080GTX.

Hello, Can you help to upload the dataset to BaiDuNetwork disk , I can't download it from GoogleDrive, Thanks a lot!

**Comment by Harsharma2308** [comment]
Hi could someone share the trained model h5 files?

**Comment by NoviceCrom** [comment]
> I spent about 8 minutes to test the GoPro dataset, which has 1111 test images with a size of 720×1280.  I use 1080GTX.
> And testing a 256×256 image run fast.

Hi, Testing on GoPro dataset costs me a long time on RTX 2060. Is there any suggestions to accelerate that?

**Comment by yinglili666** [comment]
> yes, I retrained the network, it generated the file "best_fpn.h5" and "lasted_fpn.h5".

hello, I want to ask you about training the network. I don't know how to change che config file, could you please tell me the method to train? And can you send me the trained model? thank you!
