### ISSUE TITLE
When test GoPro dataset，What is the test image size？

### ISSUE THREAD

**Issue by yff0815** [TAMU-VITA/DeblurGANv2#57]
Hello ，good work, but I have a question.
The size of the original images is 1280*720 in the GoPro test dataset, and I would like to know what is the test image size When we test the net in this paper? Should we put 256 * 256 in or 1280 * 720?
what is the linear image subset in the picture below? Looking forward to your reply!
![image](https://user-images.githubusercontent.com/41831614/78227909-93e61280-7500-11ea-91a7-83ad5ecc353e.png)

**Comment by Sandbox3aster** [comment]
Hi,
Thanks for you interest!
(1) It's 1280 * 720
(2) Gopro dataset has gamma corrected and not corrected (linear CRF) version, Here the linear image subset correspond to the later.
See more here https://seungjunnah.github.io/Datasets/gopro
