### ISSUE TITLE
loss_D = self.adv_lambda * self.adv_trainer.lossD(outputs, targets) AttributeError: 'DoubleGAN' object has no attribute 'lossD'

### ISSUE THREAD

**Issue by Chaway** [TAMU-VITA/DeblurGANv2#6]
'lossD' should be replaced by ‘loss_d’ ?

**Comment by Sandbox3aster** [comment]
Sorry, there is still some bugs for this version, just change all "lossD" to "loss_D"

**Comment by t-martyniuk** [comment]
already fixed in current version of train.py

**Comment by Chaway** [comment]
> already fixed in current version of train.py

Thanks! @t-martyniuk
