### ISSUE TITLE
Have any one meet the predicted results with pale purple spot？

### ISSUE THREAD

**Issue by guocefeng** [TAMU-VITA/DeblurGANv2#61]
I have gotten predicted results(images) with pale purple spot, which presented randomly when using the pre-trained model named "InceptionResNet-v2" or "fpn_inception.h5"(download). 

In addition, the phenomenon also exists when using the model trained on my own dataset. I set  ['model']['g_name'] "fpn_inception" in config/config.yaml and used other default settings when training.

Furthermore, when using “fpn_mobilenet”, there is no such problem.

Anyone who has found the cause of this problem would be most grateful for your sharing！Thanks.
![Selection_030](https://user-images.githubusercontent.com/52403450/79197231-f7a6fe80-7e63-11ea-9ebd-780c4ac909ef.png)

**Comment by htleeab** [comment]
I also met this issue.
https://github.com/TAMU-VITA/DeblurGANv2/issues/18#issuecomment-611360975
@KupynOrest @t-martyniuk said it was bug in the inference and updated the pre-trained model, but seems still occurs on other testing images.

**Comment by guocefeng** [comment]
@htleeab Much thx.

**Comment by Sandbox3aster** [comment]
merged with Issue #18
