### ISSUE TITLE
cannot import name 'inceptionresnetv2' from 'pretrainedmodels' (unknown location)

### ISSUE THREAD

**Issue by Loreaks** [TAMU-VITA/DeblurGANv2#65]
May I get the latest one? I would be very appreciate it!

**Comment by suke27** [comment]
do you resolve this problem?

**Comment by Loreaks** [comment]
> do you resolve this problem?

not yet

**Comment by t-martyniuk** [comment]
https://github.com/TAMU-VITA/DeblurGANv2/issues/43

take a look here
