### ISSUE TITLE
Inference time is slower than the one reported in the paper 

### ISSUE THREAD

**Issue by wonwoolee** [TAMU-VITA/DeblurGANv2#68]
Hi, 
I tried your code with fpn_mobilenet.h5, and it is supposed to run in 60ms on 1280x720 image, as reported in the paper. 
However, inference took about 250ms when I measured timings on gtx1080. 

The way I measure inference time is as below: 
`from datetime import datetime as dt`
`begin = dt.now()`        
`result = predictor(im, None)`
`duration = (dt.now() - begin).total_seconds()`

Am I doing this in a right way, or is there another way to measure inference time?

**Comment by wubo1195858658** [comment]
应该是把，我用256×256的也60ms 基本对的上论文中的

**Comment by wonwoolee** [comment]
Hi, Thanks for the answer
Since I cannot read Chinese I used a translator to understand it. 

As I understood, the timings of 60ms inference time in the paper is measured on a 256x256 size patch, not the full 1280x720 resolution. Do I understand your answer correctly?

**Comment by wubo1195858658** [comment]
是的，而且在计算用时需要在result行下面添加 torch.cuda.synchronize() ，等待torch在GPU上的操作完成在计算时间

**Comment by wubo1195858658** [comment]
不过我在2080Ti上测试，确认过速度确实是40ms即可

**Comment by wonwoolee** [comment]
Hi, sorry for bordering you on this. 
Did you achieve 40ms on 2080Ti with 256x256 patch or 1280x720 full image ?

I'm a bit confused here. The paper says DeblurGAN-v2(MobileNet) achieved 0.06s on 1280x720 image in Table 2 and 3, while you mentioned that you used 256x256 patch to measure timings in the previous comment. 

Would you please confirm what the resolution of an input image is, when you measure the timings reported in the paper?

**Comment by wubo1195858658** [comment]
我一开始在自己电脑验证，由于电脑是2G，算力比较差，验证出来256大小的补丁 耗时是0.07s

**Comment by 707278645** [comment]
> 不过我在2080Ti上测试，确认过速度确实是40ms即可
你好我想问问推理效率是怎么计算的呢   it/s 是看测试的时候还是看训练的呢  这个记过跟batchsize有关 您设置的是1吗

**Comment by wubo1195858658** [comment]
我的做法是测试的时候，将Batch Size设1，用的是Pytorch框架，在测试 推理的时候进行评估时间

**Comment by 707278645** [comment]
> > 不过我在2080Ti上测试，确认过速度确实是40ms即可
> > 你好我想问问推理效率是怎么计算的呢   it/s 是看测试的时候还是看训练的呢  这个记过跟batchsize有关 您设置的是1吗
谢谢，那您训练的时候batchsize也是设置的1吗  我设置了不同批次的batchsize 好像只有1的时候训练的模型最好

**Comment by 707278645** [comment]
> 我的做法是测试的时候，将批处理大小设置1，用的是Pytorch框架，在测试推理的时候进行评估时间
谢谢，那您训练的时候batchsize也是设置的1吗 我设置了不同批次的batchsize 好像只有1的时候训练的模型最好

**Comment by wubo1195858658** [comment]
讨论区不是很多人复现和测试了吗？效果不是不好吗？  我也没有复现 我只是测试了速度而已

**Comment by 707278645** [comment]
可以将测试时间的代码公布吗

**Comment by 707278645** [comment]
> 我的做法是测试的时候，将批处理大小设置1，用的是Pytorch框架，在测试推理的时候进行评估时间

推理时间的代码可以公布吗

**Comment by wonwoolee** [comment]
Thanks for all your answers !

**Comment by shen494157765** [comment]
> Hi, sorry for bordering you on this. Did you achieve 40ms on 2080Ti with 256x256 patch or 1280x720 full image ?
> 
> I'm a bit confused here. The paper says DeblurGAN-v2(MobileNet) achieved 0.06s on 1280x720 image in Table 2 and 3, while you mentioned that you used 256x256 patch to measure timings in the previous comment.
> 
> Would you please confirm what the resolution of an input image is, when you measure the timings reported in the paper?

Hi,

How can you guys inference the model with image size 720x1280 ?

It will be an error if you use the image with 720x1280 when the backbone of model is mobilenet.

and the error was caused by the upsample feature map size.

Thanks

**Comment by wubo1195858658** [comment]
DeblurGAN-v2(MobileNet) does achieve 60 milliseconds at 720P
