### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by f4hxm** [TAMU-VITA/DeblurGANv2#7]
Could you provide test.py?

**Comment by xytmhy** [comment]
Agreed. I want to use the test.sh but get   
File "/home/lsj/PycharmProjects/ComparisonDeblur/DeblurGANv2-master/dataset.py", line 123, in from_config
    corrupt_fn = aug.get_corrupt_function(config=config['corrupt'])
KeyError: 'corrupt'

Besides, I miss where to change the path of pretrianed model and dataset. Maybe a clear test.py would be really helpful.

**Comment by t-martyniuk** [comment]
please try predict.py for testing purposes.
