### ISSUE TITLE
What version of python does this code use?

### ISSUE THREAD

**Issue by DMSalvatore** [TAMU-VITA/DeblurGANv2#71]
When I try this code with its test, SyntaxError: invalid syntax exists as follow:
![image](https://user-images.githubusercontent.com/48174576/87869373-e1b05900-c9d1-11ea-8cea-531dcbe3a1ff.png)

**Comment by OdysseeT** [comment]
I use it with Python 3.7 it works well
And:
torch==1.5.1
torchsummary==1.5.1
torchvision==0.6.1

**Comment by Sandbox3aster** [comment]
You should use python >=3.6, will add in requirements
