### ISSUE TITLE
the net input size

### ISSUE THREAD

**Issue by f4hxm** [TAMU-VITA/DeblurGANv2#9]
The size of original images is 1280*720,  When we test the net, should we put 256 * 256 in or 1280 * 720?

**Comment by f4hxm** [comment]
When we test the net, should we put 256 * 256 in or 1280 * 720?
when we train net, we use albu.ShiftScaleRotate, the scale in [-0.1, 0.1]?

**Comment by xytmhy** [comment]
I think original image size would be fine, since it's a FCN net. 
By the way, do you know how to test in our images. I fail to find where to change the path of dataset.

**Comment by f4hxm** [comment]
> I think original image size would be fine, since it's a FCN net.
> By the way, do you know how to test in our images. I fail to find where to change the path of dataset.

you can change the path of dataset in config/config.yaml.

**Comment by congratulation888** [comment]
> > I think original image size would be fine, since it's a FCN net.
> > By the way, do you know how to test in our images. I fail to find where to change the path of dataset.
> 
> you can change the path of dataset in config/config.yaml. The author doesn't provide test.py.



> The size of original images is 1280*720, When we test the net, should we put 256 * 256 in or 1280 * 720?

how do you run the test.py?

**Comment by t-martyniuk** [comment]
you have predict.py file now for testing. please check the latest updates.
